# Generated by Django 4.1.1 on 2022-10-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('category', models.CharField(choices=[('I', 'Italian'), ('V', 'Vegetarian'), ('B', 'Burger'), ('A', 'Asian')], max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=70)),
                ('zip', models.IntegerField()),
                ('website', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('opening_hours', models.TextField()),
                ('price_level', models.CharField(choices=[('$', 'cheap'), ('$$', 'medium'), ('$$$', 'expensive'), ('$$$$', 'super expensive')], max_length=10)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
