# Generated by Django 4.1.1 on 2022-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_created_restaurant_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
